# Generated by Django 4.1.3 on 2025-02-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_noticia_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='titulo',
        ),
    ]
