# Generated by Django 5.1.6 on 2025-02-22 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_noticia_titulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'verbose_name': 'Notícia', 'verbose_name_plural': 'Notícias'},
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='data_publicacao',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='links',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='nome_imagem',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='tipo_imagem',
        ),
    ]
