# Generated by Django 5.1.6 on 2025-02-27 23:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_noticia_options_remove_noticia_data_publicacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='data_publicacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
