# Generated by Django 4.1.3 on 2025-02-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('links', models.URLField(blank=True, max_length=500, null=True)),
                ('imagem', models.BinaryField(blank=True, null=True)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('nome_imagem', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_imagem', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
