tasks:
  - id: "pesquisa_noticias"
    name: "Pesquisar Notícias da Semana"
    agent: news_researcher
    description: "Pesquisar 5 notícias relevantes de tecnologia a partir de {{ data|date:'Y-m-d'|safe }}. IMPORTANTE: Faça buscas eficientes para encontrar notícias diversas e relevantes de diferentes áreas da tecnologia. Cada notícia deve ser de uma fonte confiável, incluir título, data de publicação e URL da fonte. Priorize notícias recentes e impactantes."
    expected_output: "Lista com 5 notícias diferentes de tecnologia da semana atual, cada uma contendo: título, fonte, data de publicação e URL."
    tools: ["web_search"]
    context: []

  - id: "pesquisa_tendencias"
    name: "Análise de Tendências"
    agent: news_researcher
    description: "Analisar as tendências tecnológicas emergentes relacionadas às 5 notícias encontradas. IMPORTANTE: Use apenas as informações já obtidas na pesquisa anterior e seu conhecimento existente, evitando novas buscas."
    expected_output: "Breve análise contextual das tendências identificadas nas notícias, com foco em impactos futuros."
    tools: []
    context: ["pesquisa_noticias"]

  - id: "redigir_noticias"
    name: "Redigir Notícias"
    agent: news_writer
    description: "Criar 5 artigos em markdown a partir das 5 notícias diferentes encontradas. Cada artigo deve apresentar a notícia de forma clara e informativa, incluindo título, data e fonte original. Use apenas as informações já obtidas nas pesquisas anteriores. As noticias devem ter tamanhos relacionados aos tamanhos das noticias do site, não crie noticias com tamanhos padrão."
    expected_output: |
      # Notícias de Tecnologia da Semana

      ## [Título da Notícia 1]
      [Texto da notícia 1]
      Fonte: [nome da fonte] - [link]
      Data: [data_publicacao]

      ## [Título da Notícia 2]
      [Texto da notícia 2]
      Fonte: [nome da fonte] - [link]
      Data: [data_publicacao]

      ## [Título da Notícia 3]
      [Texto da notícia 3]
      Fonte: [nome da fonte] - [link]
      Data: [data_publicacao]

      ## [Título da Notícia 4]
      [Texto da notícia 4]
      Fonte: [nome da fonte] - [link]
      Data: [data_publicacao]

      ## [Título da Notícia 5]
      [Texto da notícia 5]
      Fonte: [nome da fonte] - [link]
      Data: [data_publicacao]

    context: ["pesquisa_noticias"]

  - id: "revisar_conteudo"
    name: "Revisar e Consolidar"
    agent: editor
    description: "Revisar, formatar e consolidar as 5 notícias em um único documento coeso em markdown, adequado para exibição web. Cada notícia deve ter título, conteúdo, data e fonte claramente identificados."
    expected_output: |
      <h1>Notícias de Tecnologia da Semana</h1>

      <h2>[Título da Notícia 1]</h2>
      <p>[Texto da notícia 1]</p>
      <p>[Data da publicação]</p>
      <p><small>Fonte: <a href="[link]" target="_blank">[fonte]</a></small></p>

      <h2>[Título da Notícia 2]</h2>
      <p>[Texto da notícia 2]</p>
      <p>[Data da publicação]</p>
      <p><small>Fonte: <a href="[link]" target="_blank">[fonte]</a></small></p>

      <h2>[Título da Notícia 3]</h2>
      <p>[Texto da notícia 3]</p>
      <p>[Data da publicação]</p>
      <p><small>Fonte: <a href="[link]" target="_blank">[fonte]</a></small></p>

      <h2>[Título da Notícia 4]</h2>
      <p>[Texto da notícia 4]</p>
      <p>[Data da publicação]</p>
      <p><small>Fonte: <a href="[link]" target="_blank">[fonte]</a></small></p>

      <h2>[Título da Notícia 5]</h2>
      <p>[Texto da notícia 5]</p>
      <p>[Data da publicação]</p>
      <p><small>Fonte: <a href="[link]" target="_blank">[fonte]</a></small></p>

    context: ["redigir_noticias"]
