tasks:
  - id: "pesquisa_noticias"
    name: "Pesquisar Notícias do Dia"
    agent: news_researcher
    description: "Pesquisar uma notícia relevante de tecnologia do dia {{ data|date:'Y-m-d'|safe }} e criar 5 ângulos diferentes para ela. Priorize uma fonte confiável e uma notícia impactante do ano de 2025 que possa gerar múltiplos desdobramentos."
    expected_output: "Uma notícia principal com 5 ângulos diferentes de análise, incluindo: título principal, fonte, data, e os diferentes aspectos a serem explorados."
    tools: ["web_search"]
    context: []

  - id: "pesquisa_tendencias"
    name: "Análise de Tendências"
    agent: news_researcher
    description: "Analisar as tendências tecnológicas emergentes relacionadas à notícia principal e seus desdobramentos para o ano de 2025."
    expected_output: "Análise contextual das tendências identificadas na notícia principal e seus desdobramentos, com foco em impactos futuros."
    tools: ["web_search"]
    context: ["pesquisa_noticias"]

  - id: "redigir_noticias"
    name: "Redigir Notícias"
    agent: news_writer
    description: "Criar 5 artigos em markdown a partir da notícia principal e seus diferentes ângulos para {{ data|date:'Y-m-d'|safe }}. Cada artigo deve explorar um aspecto diferente da notícia principal."
    expected_output: |
      # Notícias de Tecnologia do Dia

      ## [Título da Notícia Principal]
      [Texto explorando o primeiro ângulo]
      Fonte: [link]
      Data: [data_publicacao]

      ## [Título do Desdobramento 1]
      [Texto explorando o segundo ângulo]

      ## [Título do Desdobramento 2]
      [Texto explorando o terceiro ângulo]

      ## [Título do Desdobramento 3]
      [Texto explorando o quarto ângulo]

      ## [Título do Desdobramento 4]
      [Texto explorando o quinto ângulo]

    context: ["pesquisa_noticias"]

  - id: "revisar_conteudo"
    name: "Revisar e Consolidar"
    agent: editor
    description: "Revisar, formatar e consolidar os 5 artigos em um único artigo coeso em markdown, adequado para exibição web.
    Cada artigo deve ter no mínimo 3 parágrafos, mas o tamanho deve variar de acordo com a relevância do ângulo explorado."
    expected_output: |
      <h1>Notícias de Tecnologia</h1>

      <h2>[Título Principal]</h2>
      <p>[Texto principal]</p>
      <p>[Data da publicação]</p>
      <p><small>Fonte: <a href="[link]" target="_blank">[fonte]</a></small></p>

      <h2>[Título do Desdobramento]</h2>
      <p>[Texto do desdobramento]</p>

    context: ["redigir_noticias"]
